/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
'use client'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function OfficeScene(props) {
  const { nodes, materials } = useGLTF('/models/office.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Arcade_Cabinet.geometry}
        material={materials.ArcadeMaterial}
        position={[-9.147, -0.113, 9.218]}
        rotation={[0, -0.475, 0]}
        scale={1.079}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bolt010.geometry}
          material={materials.ArcadeMaterial}
          position={[-1.463, 6.012, -1.496]}
          rotation={[Math.PI / 2, 0, 1.562]}
          scale={0.108}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder011.geometry}
          material={materials.ArcadeMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder012.geometry}
          material={materials.ArcadeMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder020.geometry}
          material={materials.ArcadeMaterial}
          position={[0, 2.869, -0.357]}
          rotation={[0, -1.562, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder029.geometry}
          material={materials.ArcadeMaterial}
          position={[0, 2.869, -0.357]}
          rotation={[0, -1.562, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder042.geometry}
          material={materials.ArcadeMaterial}
          position={[0, 2.869, -0.357]}
          rotation={[0, -1.562, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text.geometry}
          material={materials.ArcadeMaterial}
          position={[1.074, 5.687, -1.553]}
          rotation={[Math.PI / 2, 0, 3.133]}
          scale={[0.445, 0.445, 0.378]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text002.geometry}
          material={materials.ArcadeMaterial}
          position={[1.047, 5.93, -1.576]}
          rotation={[Math.PI / 2, 0, 3.133]}
          scale={[0.095, 0.095, 0.08]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text003.geometry}
          material={materials.ArcadeMaterial}
          position={[-0.506, 5.615, -1.553]}
          rotation={[Math.PI / 2, 0, 3.133]}
          scale={[0.095, 0.095, 0.08]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text004.geometry}
          material={materials.ArcadeMaterial}
          position={[-1.505, 1.343, -0.604]}
          rotation={[0.893, 0.005, 1.564]}
          scale={[0.195, 0.195, 0.166]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text005.geometry}
          material={materials.ArcadeMaterial}
          position={[1.485, 2.326, 0.568]}
          rotation={[0.915, 0.005, -1.578]}
          scale={[0.195, 0.195, 0.166]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ArcadeScreen.geometry}
        material={materials.ArcadeMaterial}
        position={[-8.833, 3.047, 8.643]}
        rotation={[Math.PI, -1.104, Math.PI]}
        scale={[0.922, 2.975, 1.496]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials.ArcadeMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Couch.geometry}
        material={materials.ArcadeMaterial}
        position={[0.491, 0, -2.005]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.retro_computer_setup.geometry}
        material={materials.ArcadeMaterial}
        position={[0.926, 3.208, 7.407]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.computer_screen.geometry}
        material={materials.ArcadeMaterial}
        position={[1.395, 3.949, 8.022]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.ArcadeMaterial}
        position={[-4.162, 1.351, -7.268]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tige.geometry}
        material={materials.ArcadeMaterial}
        position={[9.371, 1.525, 7.531]}
        scale={1.303}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pot.geometry}
        material={materials.ArcadeMaterial}
        position={[9.352, 0.852, 7.583]}
        scale={1.303}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf014.geometry}
        material={materials.ArcadeMaterial}
        position={[8.755, 5.194, 7.338]}
        scale={1.303}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf004.geometry}
        material={materials.ArcadeMaterial}
        position={[9.495, 6.261, 8.212]}
        scale={1.303}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf003.geometry}
        material={materials.ArcadeMaterial}
        position={[9.716, 3.422, 7.478]}
        scale={1.303}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials.ArcadeMaterial}
        position={[3.055, 0.363, -5.796]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pot001.geometry}
        material={materials.ArcadeMaterial}
        position={[9.383, 0.852, 7.583]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube026.geometry}
        material={materials['Material.023']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube026_1.geometry}
        material={materials['Material.034']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube026_2.geometry}
        material={materials['Material.039']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube026_3.geometry}
        material={materials['Material.030']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube031.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube031_1.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube031_2.geometry}
        material={materials['Material.031']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube031_3.geometry}
        material={materials['Material.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube031_4.geometry}
        material={materials['Material.017']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube031_5.geometry}
        material={materials['Material.018']}
      />
    </group>
  )
}

useGLTF.preload('/models/office.glb')